#!/bin/zsh

source ~/.cache/wal/colors.sh

blurred_wallaper_path="/home/adil/.cache/wallpaperblur/$(basename "$wallpaper")"

filename=$(basename -- "$wallpaper")
extension="${filename##*.}"
filename="${filename%.*}"

echo $extension
echo $filename

# for i in $(seq 10)
# do
#   blurred_wallaper_path="/home/adil/.cache/wallpaperblur/$filename$i.$extension"
#   echo $blurred_wallaper_path
#   feh --bg-fill "$blurred_wallaper_path"
# done

for i in $(seq 10 -1 1)
do
  blurred_wallaper_path="/home/adil/.cache/wallpaperblur/$filename$i.$extension"
  echo $blurred_wallaper_path
  feh --bg-fill "$blurred_wallaper_path"
done
feh --bg-fill "$wallpaper"